import { PropertyCard } from '@/api/types/property.type'

export const mockProperties: PropertyCard[] = [
  {
    id: '1',
    title: 'Modern Apartment in District 1',
    description:
      'Beautiful modern apartment with city view, fully furnished and ready to move in. Perfect for young professionals.',
    address: '123 Nguyen Hue Street',
    city: 'Ho Chi Minh City',
    property_type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    price: 15000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 80,
    furnishing: 'Fully Furnished',
    amenities: ['Air Conditioning', 'WiFi', 'Parking', 'Gym', 'Swimming Pool'],
    verified: true,
  },
  {
    id: '2',
    title: 'Cozy Studio in Binh Thanh',
    description:
      'Perfect for young professionals, close to university and business district. Modern amenities included.',
    address: '456 Dien Bien Phu Street',
    city: 'Ho Chi Minh City',
    property_type: 'Studio',
    bedrooms: 1,
    bathrooms: 1,
    price: 8000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 35,
    furnishing: 'Semi-Furnished',
    amenities: ['WiFi', 'Air Conditioning', 'Security'],
    verified: false,
  },
  {
    id: '3',
    title: 'Luxury Villa in Thu Duc',
    description:
      'Spacious villa with garden, perfect for families. Private and secure with premium amenities.',
    address: '789 Vo Van Ngan Street',
    city: 'Ho Chi Minh City',
    property_type: 'Villa',
    bedrooms: 4,
    bathrooms: 3,
    price: 25000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 200,
    furnishing: 'Fully Furnished',
    amenities: ['Garden', 'Parking', 'Security', 'Swimming Pool', 'Gym'],
    verified: true,
  },
  {
    id: '4',
    title: 'Budget Room in Tan Binh',
    description:
      'Affordable room for students and young workers. Shared facilities and utilities included.',
    address: '321 Cach Mang Thang 8',
    city: 'Ho Chi Minh City',
    property_type: 'Room',
    bedrooms: 1,
    bathrooms: 1,
    price: 4000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 20,
    furnishing: 'Basic',
    amenities: ['WiFi', 'Shared Kitchen', 'Security'],
    verified: false,
  },
  {
    id: '5',
    title: 'Premium Condo in District 7',
    description:
      'High-end condominium with panoramic city views. Premium location with luxury amenities.',
    address: '555 Nguyen Thi Thap',
    city: 'Ho Chi Minh City',
    property_type: 'Condo',
    bedrooms: 3,
    bathrooms: 2,
    price: 22000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 120,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
    ],
    verified: true,
  },
  {
    id: '6',
    title: 'Family House in Go Vap',
    description:
      'Traditional Vietnamese house with modern upgrades. Perfect for families with children.',
    address: '888 Quang Trung',
    city: 'Ho Chi Minh City',
    property_type: 'House',
    bedrooms: 3,
    bathrooms: 2,
    price: 18000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 150,
    furnishing: 'Semi-Furnished',
    amenities: ['Garden', 'Parking', 'Security'],
    verified: true,
  },
  {
    id: '7',
    title: 'Modern Loft in District 2',
    description:
      'Industrial-style loft with high ceilings and open space. Creative workspace included.',
    address: '999 Thao Dien',
    city: 'Ho Chi Minh City',
    property_type: 'Loft',
    bedrooms: 2,
    bathrooms: 1,
    price: 12000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 60,
    furnishing: 'Fully Furnished',
    amenities: ['Air Conditioning', 'WiFi', 'Parking', 'Balcony'],
    verified: false,
  },
  {
    id: '8',
    title: 'Shared Apartment in District 3',
    description:
      'Shared living space with private room. Great for networking and making friends.',
    address: '777 Le Van Sy',
    city: 'Ho Chi Minh City',
    property_type: 'Shared',
    bedrooms: 1,
    bathrooms: 1,
    price: 6000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 25,
    furnishing: 'Fully Furnished',
    amenities: ['WiFi', 'Shared Kitchen', 'Shared Living Room', 'Security'],
    verified: false,
  },
]
