import { PropertyCard } from '@/api/types/property.type'

export const mockProperties: PropertyCard[] = [
  {
    id: '1',
    title: 'Modern Apartment in District 1',
    description:
      'Beautiful modern apartment with city view, fully furnished and ready to move in. Perfect for young professionals.',
    address: '123 Nguyen Hue Street',
    city: 'Ho Chi Minh City',
    property_type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    price: 15000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 80,
    furnishing: 'Fully Furnished',
    amenities: ['Air Conditioning', 'WiFi', 'Parking', 'Gym', 'Swimming Pool'],
    verified: true,
  },
  {
    id: '2',
    title: 'Cozy Studio in Binh Thanh',
    description:
      'Perfect for young professionals, close to university and business district. Modern amenities included.',
    address: '456 Dien Bien Phu Street',
    city: 'Ho Chi Minh City',
    property_type: 'Studio',
    bedrooms: 1,
    bathrooms: 1,
    price: 8000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 35,
    furnishing: 'Semi-Furnished',
    amenities: ['WiFi', 'Air Conditioning', 'Security'],
    verified: false,
  },
  {
    id: '3',
    title: 'Luxury Villa in Thu Duc',
    description:
      'Spacious villa with garden, perfect for families. Private and secure with premium amenities.',
    address: '789 Vo Van Ngan Street',
    city: 'Ho Chi Minh City',
    property_type: 'Villa',
    bedrooms: 4,
    bathrooms: 3,
    price: 25000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 150,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
      'Garden',
    ],
    verified: true,
  },
  {
    id: '4',
    title: 'Modern House in District 7',
    description:
      'Newly built house with modern design, perfect for families looking for comfort and style.',
    address: '321 Nguyen Van Linh',
    city: 'Ho Chi Minh City',
    property_type: 'House',
    bedrooms: 3,
    bathrooms: 2,
    price: 18000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 120,
    furnishing: 'Semi-Furnished',
    amenities: ['Air Conditioning', 'WiFi', 'Parking', 'Garden', 'Security'],
    verified: false,
  },
  {
    id: '5',
    title: 'Luxury Condo in District 2',
    description:
      'High-end condo with river view, premium amenities and concierge service. Perfect for executives.',
    address: '654 Nguyen Thi Minh Khai',
    city: 'Ho Chi Minh City',
    property_type: 'Condo',
    bedrooms: 2,
    bathrooms: 2,
    price: 20000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 90,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
      'Concierge',
    ],
    verified: true,
  },
  {
    id: '6',
    title: 'Townhouse in Go Vap',
    description:
      'Traditional townhouse with modern renovation, perfect for families who want space and privacy.',
    address: '987 Quang Trung',
    city: 'Ho Chi Minh City',
    property_type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 2,
    price: 16000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 110,
    furnishing: 'Unfurnished',
    amenities: ['Parking', 'Garden', 'Security'],
    verified: false,
  },
  {
    id: '7',
    title: 'Penthouse in District 1',
    description:
      'Luxury penthouse with panoramic city view, premium finishes and exclusive amenities.',
    address: '147 Dong Khoi',
    city: 'Ho Chi Minh City',
    property_type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 3,
    price: 40000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 200,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
      'Balcony',
      'Concierge',
    ],
    verified: true,
  },
  {
    id: '8',
    title: 'Shared Living Space',
    description:
      'Shared living space with private room. Great for networking and making friends.',
    address: '777 Le Van Sy',
    city: 'Ho Chi Minh City',
    property_type: 'Shared',
    bedrooms: 1,
    bathrooms: 1,
    price: 6000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 25,
    furnishing: 'Fully Furnished',
    amenities: ['WiFi', 'Shared Kitchen', 'Shared Living Room', 'Security'],
    verified: false,
  },
  {
    id: '9',
    title: 'Premium Apartment in District 2',
    description:
      'High-end apartment with river view, perfect for executives and expats.',
    address: '888 Nguyen Thi Minh Khai',
    city: 'Ho Chi Minh City',
    property_type: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    price: 18000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 95,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
    ],
    verified: true,
  },
  {
    id: '10',
    title: 'Modern Condo in District 7',
    description:
      'Newly built condo with modern design and smart home features.',
    address: '999 Nguyen Van Linh',
    city: 'Ho Chi Minh City',
    property_type: 'Condo',
    bedrooms: 2,
    bathrooms: 2,
    price: 12000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 70,
    furnishing: 'Semi-Furnished',
    amenities: ['Air Conditioning', 'WiFi', 'Parking', 'Gym'],
    verified: true,
  },
  {
    id: '11',
    title: 'Townhouse in Go Vap',
    description:
      'Traditional townhouse with modern renovation, perfect for families.',
    address: '111 Quang Trung',
    city: 'Ho Chi Minh City',
    property_type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 2,
    price: 16000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 120,
    furnishing: 'Unfurnished',
    amenities: ['Parking', 'Garden', 'Security'],
    verified: false,
  },
  {
    id: '12',
    title: 'Penthouse in District 1',
    description:
      'Luxury penthouse with panoramic city view and premium amenities.',
    address: '222 Dong Khoi',
    city: 'Ho Chi Minh City',
    property_type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 3,
    price: 35000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 200,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
      'Balcony',
    ],
    verified: true,
  },
  {
    id: '13',
    title: 'Cozy House in Tan Binh',
    description:
      'Charming house in quiet neighborhood, perfect for small families.',
    address: '333 Cach Mang Thang 8',
    city: 'Ho Chi Minh City',
    property_type: 'House',
    bedrooms: 2,
    bathrooms: 1,
    price: 10000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 60,
    furnishing: 'Semi-Furnished',
    amenities: ['WiFi', 'Parking', 'Garden'],
    verified: false,
  },
  {
    id: '14',
    title: 'Studio in Phu Nhuan',
    description: 'Compact studio perfect for students and young professionals.',
    address: '444 Phan Dang Luu',
    city: 'Ho Chi Minh City',
    property_type: 'Studio',
    bedrooms: 1,
    bathrooms: 1,
    price: 7000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 30,
    furnishing: 'Fully Furnished',
    amenities: ['WiFi', 'Air Conditioning'],
    verified: false,
  },
  {
    id: '15',
    title: 'Luxury Apartment in District 3',
    description:
      'High-end apartment with premium finishes and concierge service.',
    address: '555 Vo Van Tan',
    city: 'Ho Chi Minh City',
    property_type: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    price: 20000000,
    currency: 'VND',
    images: ['/images/example.png'],
    area: 110,
    furnishing: 'Fully Furnished',
    amenities: [
      'Air Conditioning',
      'WiFi',
      'Parking',
      'Gym',
      'Swimming Pool',
      'Security',
      'Concierge',
    ],
    verified: true,
  },
]
